# Usar a imagem oficial do Python mais recente
FROM python:3.9-slim

# Instalar dependências do sistema e bibliotecas necessárias
RUN apt-get update && apt-get install -y \
    curl \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Definir o diretório de trabalho
WORKDIR /app

# Copiar o restante do código do projeto para o diretório de trabalho no contêiner
COPY ../app/ /app/

# Instalar as dependências do projeto diretamente
RUN pip install --no-cache-dir \
    Flask \
    python-dotenv \
    mysql-connector-python \
    uvicorn \
    openai \
    flask_sqlalchemy \
    pymysql\
    psycopg2-binary 
    
# Expor a porta 8000 para o Uvicorn
EXPOSE 8000

# Iniciar o Uvicorn com o Flask (alterando o caminho para o arquivo main.py)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]